Repository datawowio/nextjs-template, pull requests merged in 2024-09, with the labels that each got.

#39 Add typography config with custom variant
  .storybook/preview.ts
  src/app/[locale]/layout.tsx
  src/components/core/typography/Typography.stories.tsx
  src/components/core/typography/Typography.tsx
  src/components/core/typography/helpers.ts
  src/components/core/typography/index.ts
  src/components/core/typography/styles.ts
  src/components/core/typography/types.ts
  src/components/web-vitals/WebVitals.tsx
  src/components/web-vitals/index.ts
  src/config/fonts.ts
  src/contexts/theme.ts
  src/screens/home/HomeScreen.tsx
  src/styles/global.css
  src/styles/index.ts
Labels: Reviews, Chore

#42 Update README
  README.md
Labels: Chore

#43 chore: configure color template
  src/components/core/card-color/CardColor.stories.tsx
  src/components/core/card-color/CardColor.tsx
  src/components/core/card-color/styles.ts
  src/components/core/card-color/types.ts
  src/config/palette.ts
  src/contexts/theme.ts
  src/styles/global.css
Labels: Chore

#46 chore: create button component
  src/components/core/button/Button.stories.tsx
  src/components/core/button/Button.tsx
  src/components/core/button/index.ts
  src/components/core/button/types.ts
  src/contexts/theme.ts
  src/screens/home/HomeScreen.tsx
  src/styles/mui/button.ts
Labels: Chore

#45 Refactor Storybook decorators and etc.
  .env.example
  .github/workflows/build_and_test.yml
  .github/workflows/deploy_storybook.yml
  .storybook/theme.ts
  README.md
  package.json
  src/components/core/button/Button.test.tsx
  src/components/core/card-color/CardColor.stories.tsx
  src/components/core/card-color/CardColor.tsx
  src/components/core/card-color/styles.ts
  src/components/core/card-color/types.ts
  src/components/core/color/Color.stories.tsx
  src/components/core/color/Color.test.tsx
  src/components/core/color/Color.tsx
  src/components/core/color/ColorSurface.test.tsx
  src/components/core/color/ColorSurface.tsx
  src/components/core/color/index.ts
  src/components/core/color/styles.ts
  src/components/core/color/types.ts
  src/components/core/typography/Typography.stories.tsx
  src/components/core/typography/Typography.test.tsx
  src/components/core/typography/Typography.tsx
  src/components/core/typography/helpers.test.ts
  src/components/core/typography/helpers.ts
  src/components/sample/index.ts
  src/components/sample/sample.tsx
  src/components/web-vitals/WebVitals.test.tsx
  src/contexts/theme.ts
  src/styles/global.css
  src/styles/mui/button.ts
  src/utils/.gitkeep
  src/utils/rem.test.ts
  src/utils/rem.ts
  yarn.lock
Labels: Ready for review, Chore

#48 chore: input component
  src/components/core/text-field/TextField.stories.tsx
  src/components/core/text-field/TextField.tsx
  src/components/core/text-field/index.ts
  src/components/core/text-field/types.ts
  src/contexts/theme.ts
  src/screens/home/HomeScreen.tsx
  src/styles/global.css
  src/styles/mui/text-field.ts
Labels: Chore

#49 Enhanced Text Field
  .github/workflows/build_and_test.yml
  .github/workflows/deploy_storybook.yml
  src/components/core/input/Input.stories.tsx
  src/components/core/input/Input.test.tsx
  src/components/core/input/Input.tsx
  src/components/core/input/index.ts
  src/components/core/input/types.ts
  src/components/core/text-field/TextField.stories.tsx
  src/components/core/text-field/TextField.tsx
  src/components/core/text-field/index.ts
  src/screens/home/HomeScreen.tsx
Labels: Chore

#55 Create Avatar component
  src/assets/images/avatar/fallback-avatar.png
  src/components/core/avatar/Avatar.stories.tsx
  src/components/core/avatar/Avatar.tsx
  src/components/core/avatar/index.ts
  src/components/core/avatar/styles.ts
  src/components/core/avatar/types.ts
Labels: Ready for review, Chore

#56 Create Checkbox component
  src/components/core/checkbox/Checkbox.stories.tsx
  src/components/core/checkbox/Checkbox.tsx
  src/components/core/checkbox/helpers.ts
  src/components/core/checkbox/index.ts
  src/components/core/checkbox/styles.ts
  src/components/core/checkbox/types.ts
  src/contexts/theme.ts
  src/styles/mui/checkbox.ts
Labels: Ready for review, Chore

#54 Create Pipeline Status component
  src/components/label-status/LabelStatus.stories.tsx
  src/components/label-status/LabelStatus.test.tsx
  src/components/label-status/LabelStatus.tsx
  src/components/label-status/index.ts
  src/components/label-status/styles.ts
  src/components/label-status/types.ts
Labels: Ready for review, Chore

#52 Create Toast component
  src/app/[locale]/layout.tsx
  src/components/core/toast/Toast.stories.tsx
  src/components/core/toast/Toast.tsx
  src/components/core/toast/index.ts
  src/components/core/toast/types.ts
  src/contexts/theme.ts
  src/contexts/toast.ts
  src/hooks/use-toast.ts
  src/providers/toast-provider/ToastProvider.tsx
  src/providers/toast-provider/index.ts
  src/providers/toast-provider/types.ts
  src/screens/home/HomeScreen.tsx
  src/styles/mui/alert.ts
Labels: Ready for review, Chore

#50 chore: select component
  src/components/core/select-multiple/SelectMultiple.stories.tsx
  src/components/core/select-multiple/SelectMultiple.tsx
  src/components/core/select-multiple/index.ts
  src/components/core/select-multiple/types.ts
  src/components/core/select/Select.stories.tsx
  src/components/core/select/Select.tsx
  src/components/core/select/index.ts
  src/components/core/select/types.ts
  src/contexts/theme.ts
  src/styles/mui/autocomplete.ts
  src/styles/mui/popper.ts
  src/styles/mui/text-field.ts
Labels: Ready for review, Chore

#51 Create Data Table Component
  jest.config.ts
  package.json
  src/components/core/icons/icon-arrow-down.tsx
  src/components/core/icons/icon-arrow-up.tsx
  src/components/core/icons/index.ts
  src/components/core/table-data/TableData.stories.tsx
  src/components/core/table-data/TableData.test.tsx
  src/components/core/table-data/TableData.tsx
  src/components/core/table-data/TableDataSurface.test.tsx
  src/components/core/table-data/TableDataSurface.tsx
  src/components/core/table-data/helpers.test.tsx
  src/components/core/table-data/helpers.tsx
  src/components/core/table-data/index.ts
  src/components/core/table-data/styles.ts
  src/components/core/table-data/types.ts
  yarn.lock
Labels: Ready for review, Feature

#59 Fix Toast component doesn't hide on storybook
  src/components/core/toast/Toast.stories.tsx
Labels: Bug

#58 Create Table pagination component
  src/components/core/pagination/NumberTypography.tsx
  src/components/core/pagination/Pagination.stories.tsx
  src/components/core/pagination/Pagination.tsx
  src/components/core/pagination/PaginationInfo.tsx
  src/components/core/pagination/index.ts
  src/components/core/pagination/types.ts
  src/contexts/theme.ts
  src/styles/mui/pagination.ts
Labels: Chore

#53 Create Confirmation Modal Component
  src/components/core/dialog-confirmation/DialogConfirmation.stories.tsx
  src/components/core/dialog-confirmation/DialogConfirmation.tsx
  src/components/core/dialog-confirmation/DialogConfirmationContent.tsx
  src/components/core/dialog-confirmation/index.ts
  src/components/core/dialog-confirmation/types.ts
  src/components/core/dialog/Dialog.stories.tsx
  src/components/core/dialog/Dialog.tsx
  src/components/core/dialog/index.ts
  src/components/core/dialog/types.ts
  src/components/core/modal/Modal.stories.tsx
  src/components/core/modal/Modal.tsx
  src/components/core/modal/index.ts
  src/components/core/modal/types.ts
  src/contexts/theme.ts
  src/locales/en/common.json
  src/locales/en/screens/home.json
  src/locales/th/common.json
  src/locales/th/screens/home.json
  src/screens/home/HomeScreen.tsx
  src/styles/global.css
  src/styles/mui/button.ts
  src/styles/mui/card.ts
  src/styles/mui/dialog.ts
Labels: Ready for review, Chore

#57 Improve code base and add tests
  .github/workflows/build_and_test.yml
  .github/workflows/deploy_storybook.yml
  package.json
  src/components/core/avatar/Avatar.stories.tsx
  src/components/core/avatar/Avatar.test.tsx
  src/components/core/avatar/Avatar.tsx
  src/components/core/checkbox/Checkbox.tsx
  src/components/core/checkbox/helpers.test.ts
  src/components/core/checkbox/helpers.ts
  src/components/core/checkbox/styles.ts
  src/components/core/dialog-confirmation/DialogConfirmation.test.tsx
  src/components/core/dialog-confirmation/DialogConfirmation.tsx
  src/components/core/dialog-confirmation/DialogConfirmationContent.test.tsx
  src/components/core/dialog-confirmation/DialogConfirmationContent.tsx
  src/components/core/dialog-confirmation/types.ts
  src/components/core/dialog/Dialog.stories.tsx
  src/components/core/dialog/Dialog.test.tsx
  src/components/core/dialog/Dialog.tsx
  src/components/core/select-multiple/SelectMultiple.stories.tsx
  src/components/core/select-multiple/SelectMultiple.test.tsx
  src/components/core/select-multiple/SelectMultiple.tsx
  src/components/core/select-multiple/types.ts
  src/components/core/select/Select.stories.tsx
  src/components/core/select/Select.test.tsx
  src/components/core/select/Select.tsx
  src/components/core/select/types.ts
  src/components/core/toast/Toast.stories.tsx
  src/components/core/toast/Toast.test.tsx
  src/components/core/toast/Toast.tsx
  src/components/core/toast/index.ts
  src/components/core/toast/types.ts
  src/components/label-status/LabelStatus.test.tsx
  src/components/label-status/LabelStatus.tsx
  src/components/label-status/styles.ts
  src/contexts/theme.ts
  src/contexts/toast.ts
  src/hooks/.gitkeep
  src/hooks/use-toast.test.tsx
  src/hooks/use-toast.ts
  src/providers/toast-provider/ToastProvider.test.tsx
  src/providers/toast-provider/ToastProvider.tsx
  src/providers/toast-provider/index.ts
  src/providers/toast-provider/types.ts
  src/screens/home/HomeScreen.tsx
  yarn.lock
Labels: Ready for review, Chore

#60 Change checkbox component to match best practice
  src/components/core/checkbox/Checkbox.test.tsx
  src/components/core/checkbox/Checkbox.tsx
  src/components/core/checkbox/index.ts
  src/components/core/checkbox/types.ts
  src/contexts/theme.ts
  src/styles/mui/checkbox.ts
  src/styles/mui/form-control-label.ts
Labels: Chore

#61 Create input password component
  src/components/input-password/InputPassword.stories.tsx
  src/components/input-password/InputPassword.test.tsx
  src/components/input-password/InputPassword.tsx
  src/components/input-password/types.ts
  src/contexts/theme.ts
  src/styles/mui/input-label.ts
  src/styles/mui/outlined-input.ts
  src/styles/mui/text-field.ts
Labels: Chore

#62 Release version 0.2.0
  .github/workflows/deploy_storybook.yml
  package.json
Labels: Release

#67 Create sidebar and navbar components
  src/components/nav-bar/NavBar.stories.tsx
  src/components/nav-bar/NavBar.test.tsx
  src/components/nav-bar/NavBar.tsx
  src/components/nav-bar/index.ts
  src/components/nav-bar/styles.ts
  src/components/nav-bar/types.ts
  src/components/side-bar/SideBar.stories.tsx
  src/components/side-bar/SideBar.test.tsx
  src/components/side-bar/SideBar.tsx
  src/components/side-bar/index.ts
  src/components/side-bar/types.ts
Labels: Ready for review, Chore

#68 Create main layout component
  src/components/layout-main/LayoutMain.stories.tsx
  src/components/layout-main/LayoutMain.test.tsx
  src/components/layout-main/LayoutMain.tsx
  src/components/layout-main/index.ts
  src/components/layout-main/styles.ts
  src/components/layout-main/types.ts
  src/components/side-bar/SideBar.tsx
  src/components/side-bar/styles.ts
  src/screens/home/styles.ts
  src/styles/mui/form-control-label.ts
Labels: Ready for review, Chore

#73 Add data test id to every component
  src/components/core/avatar/Avatar.tsx
  src/components/core/avatar/types.ts
  src/components/core/button/Button.tsx
  src/components/core/button/types.ts
  src/components/core/checkbox/Checkbox.tsx
  src/components/core/checkbox/types.ts
  src/components/core/dialog-confirmation/DialogConfirmation.tsx
  src/components/core/dialog-confirmation/types.ts
  src/components/core/dialog/Dialog.tsx
  src/components/core/dialog/types.ts
  src/components/core/input/Input.tsx
  src/components/core/input/types.ts
  src/components/core/modal/Modal.tsx
  src/components/core/modal/types.ts
  src/components/core/pagination/Pagination.tsx
  src/components/core/pagination/types.ts
  src/components/core/select-multiple/SelectMultiple.tsx
  src/components/core/select-multiple/types.ts
  src/components/core/select/Select.tsx
  src/components/core/select/types.ts
  src/components/core/table-data/TableData.tsx
  src/components/core/table-data/types.ts
  src/components/core/toast/Toast.tsx
  src/components/core/toast/types.ts
  src/components/core/typography/Typography.tsx
  src/components/core/typography/types.ts
  src/components/input-password/InputPassword.tsx
  src/components/input-password/types.ts
  src/components/label-status/LabelStatus.tsx
  src/components/label-status/types.ts
  src/components/layout-main/LayoutMain.tsx
  src/components/layout-main/types.ts
  src/components/nav-bar/NavBar.tsx
  src/components/nav-bar/types.ts
  src/components/side-bar/SideBar.tsx
  src/components/side-bar/types.ts
  src/types/components.ts
Labels: Ready for review, Chore

#72 Create main layout on app
  src/app/[locale]/(main)/layout.ts
  src/app/[locale]/(main)/user-management/page.tsx
  src/components/layout-main/LayoutMain.stories.tsx
  src/components/layout-main/LayoutMain.tsx
  src/components/logo/Logo.test.tsx
  src/components/logo/Logo.tsx
  src/components/logo/index.tsx
  src/components/logo/styles.ts
  src/components/logo/types.ts
  src/components/nav-bar/NavBar.stories.tsx
  src/layouts/layout-main/LayoutMain.tsx
  src/layouts/layout-main/index.ts
Labels: Ready for review, Chore

#74 Create header component
  src/components/core/header/Header.stories.tsx
  src/components/core/header/Header.test.tsx
  src/components/core/header/Header.tsx
  src/components/core/header/index.tsx
  src/components/core/header/types.ts
Labels: Ready for review, Chore

#77 Create user management ui
  src/app/[locale]/(main)/user-management/page.tsx
  src/components/core/dialog-confirmation/DialogConfirmation.tsx
  src/components/core/dialog-confirmation/types.ts
  src/components/core/pagination/Pagination.tsx
  src/components/core/select/Select.tsx
  src/components/core/table-data/helpers.tsx
  src/components/core/table-data/index.ts
  src/components/core/table-data/types.ts
  src/components/core/toast/Toast.tsx
  src/locales/en/common.json
  src/locales/en/screens/user-management.json
  src/locales/index.ts
  src/locales/th/common.json
  src/locales/th/screens/user-management.json
  src/screens/user-management/Filters.test.tsx
  src/screens/user-management/Filters.tsx
  src/screens/user-management/UserManagementScreen.test.tsx
  src/screens/user-management/UserManagementScreen.tsx
  src/screens/user-management/fixtures.tsx
  src/screens/user-management/index.ts
  src/screens/user-management/reducer.test.ts
  src/screens/user-management/reducer.ts
  src/screens/user-management/styles.ts
  src/screens/user-management/types.ts
  src/styles/mui/autocomplete.ts
  src/styles/mui/popper.ts
  src/types/query-params.ts
  src/types/sort.ts
Labels: Chore

#80 Create add user ui
  src/app/[locale]/(main)/users/new/page.tsx
  src/app/[locale]/(main)/users/page.tsx
  src/components/breadcrumbs/Breadcrumbs.stories.tsx
  src/components/breadcrumbs/Breadcrumbs.tsx
  src/components/breadcrumbs/index.ts
  src/components/breadcrumbs/styles.ts
  src/components/breadcrumbs/types.ts
  src/components/header/Header.tsx
  src/components/header/styles.ts
  src/components/header/types.ts
  src/components/layout-main/styles.ts
  src/components/pagination/Pagination.tsx
  src/components/pagination/PaginationInfo.tsx
  src/components/side-bar/SideBar.tsx
  src/components/side-bar/styles.ts
  src/constants/routes.ts
  src/layouts/layout-main/LayoutMain.tsx
  src/locales/en/screens/home/home.json
  src/locales/en/screens/user-management.json
  src/locales/en/screens/users/users.json
  src/locales/index.ts
  src/locales/th/screens/home/home.json
  src/locales/th/screens/user-management.json
  src/locales/th/screens/users/users.json
  src/screens/user-management/fixtures.tsx
  src/screens/user-management/index.ts
  src/screens/users/Filters.test.tsx
  src/screens/users/Filters.tsx
  src/screens/users/UsersScreen.test.tsx
  src/screens/users/UsersScreen.tsx
  src/screens/users/fixtures.tsx
  src/screens/users/index.ts
  src/screens/users/new/ActionButton.tsx
  src/screens/users/new/Filters.test.tsx
  src/screens/users/new/Filters.tsx
  src/screens/users/new/NewUsersScreen.tsx
  src/screens/users/new/fixtures.tsx
  src/screens/users/new/index.ts
  src/screens/users/new/reducer.test.ts
  src/screens/users/new/reducer.ts
  src/screens/users/new/styles.ts
  src/screens/users/new/types.ts
  src/screens/users/reducer.test.ts
  src/screens/users/reducer.ts
  src/screens/users/styles.ts
  src/screens/users/types.ts
  src/styles/global.css
Labels: WIP, Chore
