Repository datawowio/nextjs-template, pull requests merged in 2024-08, with the labels that each got.

#10 Config MUI with Next.js
  package.json
  src/app/[locale]/layout.tsx
  src/providers/mui-theme-provider/MuiThemeProvider.tsx
  yarn.lock
Labels: Chore

#11 create default home page for next.js template
  src/app/[locale]/layout.tsx
  src/app/[locale]/page.tsx
  src/app/apple-icon.png
  src/app/favicon.ico
  src/assets/fonts/.gitkeep
  src/assets/images/brands/logo.svg
  src/config/i18n.ts
  src/locales/en/pages/home.json
  src/locales/en/screens/home.json
  src/locales/th/pages/home.json
  src/locales/th/screens/home.json
  src/screens/home/home-screen.tsx
  src/screens/home/index.ts
  src/screens/home/styles.ts
Labels: Chore

#16 Remove all component tests
  src/app/[locale]/page.test.tsx
  src/config/i18n.ts
  src/locales/index.ts
  src/types/.gitkeep
  src/types/locale.ts
Labels: Chore

#12 POC best pattern for fetching data on server-side and client-side
  .env.example
  .gitignore
  src/services/base-service.test.ts
  src/services/base-service.ts
Labels: Proof of Concept

#13 @add and update packages
  package.json
  yarn.lock
Labels: Reviews

#18 Add .nvmrc, .tool-versions and yarn.lock file
  .nvmrc
  .tool-versions
  yarn.lock
Labels: Chore

#20 Update README.md and LICENSE files
  LICENSE
  README.md
Labels: Chore

#19 Add Github Action CI configration file
  .github/workflows/ci.yml
Labels: Chore

#37 Deploy Storybook to Github Page
  .github/workflows/deploy.yaml
Labels: Feature
